- MNIST 데이터를 불러올수 있는 코드는 이 외에도 다양하게 있습니다. 꼭 아래의 코드를 사용하지 않아도 됩니다.

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os as os
from sklearn.model_selection import train_test_split

In [2]:
train_orig = pd.read_csv('dataset/train.csv')
test_orig = pd.read_csv('dataset/test.csv')

In [3]:
X = train_orig.drop(['label'], axis = 1)

In [4]:
label = train_orig.label

In [5]:
y = pd.get_dummies(label, columns=['label'], drop_first=False)

In [6]:
x_train,x_test,y_train,y_test = train_test_split(X,y,test_size = 0.2, random_state = 1004)

In [7]:
print("Shape of x_train :", x_train.shape)
print("Shape of x_test :", x_test.shape)
print("Shape of y_train :", y_train.shape)
print("Shape of y_test :", y_test.shape)

Shape of x_train : (48000, 784)
Shape of x_test : (12000, 784)
Shape of y_train : (48000, 10)
Shape of y_test : (12000, 10)

In [8]:
test_orig

,label,1x1,1x2,1x3,1x4,1x5,1x6,1x7,1x8,1x9,...,28x19,28x20,28x21,28x22,28x23,28x24,28x25,28x26,28x27,28x28
0,7,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9996,3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9997,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9998,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9999,6,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0