In [45]:
import pandas as pd
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
from pandas import Series, DataFrame
import mglearn
import seaborn as sns

In [2]:
movies=pd.read_csv("C:/Users/shinyoungmin/Desktop/수DA쟁이/과제/조별과제/영화 관객수/movies.csv")

In [3]:
action=movies[movies.genre.isin(['느와르','액션'])]

In [4]:
action=action.reset_index(inplace=False)

In [5]:
print(action.screening_rat.value_counts())

청소년 관람불가    29
15세 관람가     25
12세 관람가      1
Name: screening_rat, dtype: int64

In [6]:
data=action.screening_rat

In [7]:
target=action.box_off_num

In [8]:
data_dumm=pd.get_dummies(data)

In [9]:
data_dumm

    12세 관람가  15세 관람가  청소년 관람불가
0         0        0         1
1         0        0         1
2         0        1         0
3         0        0         1
4         0        0         1
5         0        0         1
6         0        1         0
7         0        0         1
8         0        0         1
9         0        1         0
10        0        1         0
11        0        1         0
12        0        0         1
13        0        1         0
14        0        0         1
15        0        1         0
16        0        0         1
17        0        0         1
18        0        1         0
19        0        0         1
20        0        0         1
21        0        0         1
22        0        1         0
23        0        1         0
24        0        0         1
25        0        0         1
26        0        1         0
27        0        0         1
28        0        1         0
29        0        0         1
30        0        1         0
31        0        1         0
32        0        1         0
33        0        0         1
34        0        0         1
35        0        0         1
36        0        0         1
37        0        0         1
38        0        0         1
39        0        1         0
40        0        1         0
41        0        0         1
42        0        1         0
43        0        1         0
44        0        1         0
45        1        0         0
46        0        1         0
47        0        0         1
48        0        0         1
49        0        1         0
50        0        0         1
51        0        1         0
52        0        0         1
53        0        1         0
54        0        1         0

In [10]:
X=data_dumm.values

In [11]:
y=target.values

In [12]:
X.shape

(55, 3)

In [13]:
y.shape

(55,)

In [14]:
from sklearn.model_selection import train_test_split

In [15]:
X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=0)

In [16]:
from sklearn.linear_model import LinearRegression

In [17]:
from sklearn.linear_model import Ridge

In [33]:
ridge=Ridge().fit(X_train,y_train)

In [34]:
ridge.score(X_test,y_test)

-0.406904051764593

In [35]:
ridge.score(X_train,y_train)

0.13707449031573127

In [36]:
action

,index,title,distributor,genre,release_time,time,screening_rat,director,dir_prev_bfnum,dir_prev_num,num_staff,num_actor,box_off_num
0,0,개들의 전쟁,롯데엔터테인먼트,액션,2012-11-22,96,청소년 관람불가,조병옥,NaN,0,91,2,23398
1,1,내부자들,(주)쇼박스,느와르,2015-11-19,130,청소년 관람불가,우민호,1.161602e+06,2,387,3,7072501
2,2,은밀하게 위대하게,(주)쇼박스,액션,2013-06-05,123,15세 관람가,장철수,2.207752e+05,4,343,4,6959083
3,7,회사원,(주)쇼박스,액션,2012-10-11,96,청소년 관람불가,임상윤,7.395220e+05,3,342,2,1110523
4,28,무법자,(주)NEW,느와르,2010-03-18,93,청소년 관람불가,김철한,NaN,0,250,3,160734
5,44,부당거래,CJ 엔터테인먼트,느와르,2010-10-28,119,청소년 관람불가,류승완,NaN,0,471,4,2723028
6,48,빅매치,(주)NEW,액션,2014-11-26,112,15세 관람가,최호,1.159954e+06,2,600,4,1177435
7,59,친구 2,롯데엔터테인먼트,느와르,2013-11-14,124,청소년 관람불가,곽경택,3.728630e+05,2,319,3,2971475
8,74,아저씨,CJ 엔터테인먼트,액션,2010-08-04,119,청소년 관람불가,이정범,NaN,0,509,2,6178665
9,91,무적자,CJ 엔터테인먼트,액션,2010-09-16,124,15세 관람가,송해성,1.163526e+06,3,546,4,1546132
10,96,잉투기,무비꼴라쥬,액션,2013-11-14,98,15세 관람가,엄태화,NaN,0,65,3,17341
11,100,26년,인벤트 디,액션,2012-11-29,135,15세 관람가,조근현,2.636385e+06,1,365,3,2963652
12,112,범죄와의 전쟁: 나쁜놈들 전성시대,(주)쇼박스,느와르,2012-02-02,133,청소년 관람불가,윤종빈,7.195870e+05,1,308,2,4720050
13,139,고지전,(주)쇼박스,액션,2011-07-20,133,15세 관람가,장훈,2.266504e+06,3,238,11,2945151
14,141,하이프 네이션 : 힙합사기꾼,인벤트 디,느와르,2014-01-16,84,청소년 관람불가,박형우,NaN,0,6,3,3996
15,169,아이들...,롯데엔터테인먼트,느와르,2011-02-17,132,15세 관람가,이규만,NaN,0,423,5,1867849
16,175,악인은 너무 많다,어뮤즈,느와르,2011-12-15,75,청소년 관람불가,김회근,1.681556e+06,2,26,4,809
17,179,응징자,인벤트 디,액션,2013-10-30,103,청소년 관람불가,신재호,4.444850e+04,2,151,3,192347
18,182,혈투,KT,액션,2011-02-24,111,15세 관람가,박훈정,2.270048e+06,2,306,3,43947
19,188,권법형사 : 차이나타운,골든타이드픽처스,액션,2015-07-09,83,청소년 관람불가,박상현,NaN,0,151,2,257
20,198,18: 우리들의 성장 느와르,어뮤즈,느와르,2014-08-14,104,청소년 관람불가,한윤선,3.534800e+04,1,126,3,1124
21,201,강남 1970,(주)쇼박스,액션,2015-01-21,135,청소년 관람불가,유하,1.949111e+06,4,719,3,2192276
22,220,런닝맨,이십세기폭스코리아(주),액션,2013-04-04,127,15세 관람가,조동오,4.738523e+05,3,307,5,1422844
23,226,육혈포 강도단,전망좋은영화사,느와르,2010-03-18,107,15세 관람가,강효진,3.751800e+04,1,318,3,1214237
24,239,개: dog eat dog,어썸 피플,느와르,2015-03-05,101,청소년 관람불가,황욱,NaN,0,58,5,1504
25,248,철암 계곡의 혈투,인디스토리,액션,2012-07-12,89,청소년 관람불가,지하진,NaN,0,5,2,1002
26,254,특수본,롯데엔터테인먼트,액션,2011-11-24,111,15세 관람가,황병국,NaN,0,253,6,1118258
27,268,분노의 윤리학,롯데엔터테인먼트,느와르,2013-02-21,110,청소년 관람불가,박명랑,1.511050e+05,1,215,5,225618
28,320,최종병기 활,롯데엔터테인먼트,액션,2011-08-10,122,15세 관람가,김한민,2.079989e+06,1,687,4,7482180
29,358,카운트다운,NEW,액션,2011-09-29,119,청소년 관람불가,허종호,1.086916e+06,2,109,2,471547
30,361,더 폰,(주)NEW,액션,2015-10-22,114,15세 관람가,김봉주,2.500135e+06,4,437,3,1596762
31,362,도둑들,(주)쇼박스,느와르,2012-07-25,135,15세 관람가,최동훈,2.564692e+06,3,462,10,12983841
32,367,치외법권,판씨네마(주),액션,2015-08-27,104,15세 관람가,신재호,9.374800e+04,3,253,2,346483
33,377,내부자들: 디 오리지널,(주)쇼박스,느와르,2015-12-31,180,청소년 관람불가,우민호,3.131902e+06,3,382,3,2084844
34,388,공모자들,씨너스엔터테인먼트(주),느와르,2012-08-29,111,청소년 관람불가,김홍선,NaN,0,284,4,1646142
35,422,전설의 주먹,CJ 엔터테인먼트,액션,2013-04-10,153,청소년 관람불가,강우석,8.448210e+05,3,335,6,1744585
36,424,짐승,(주)키노아이,액션,2011-07-28,93,청소년 관람불가,황유식,5.064190e+05,2,54,2,480
37,429,신의 한 수,(주)쇼박스,느와르,2014-07-03,118,청소년 관람불가,조범구,1.731903e+06,2,418,5,3566844
38,442,악마를 보았다,(주)쇼박스,느와르,2010-08-12,144,청소년 관람불가,김지운,NaN,0,582,2,1817069
39,472,감시자들,(주)NEW,느와르,2013-07-03,119,15세 관람가,조의석,8.074100e+04,2,331,3,5508299
40,473,성난 변호사,CJ 엔터테인먼트,느와르,2015-10-08,117,15세 관람가,허종호,8.817930e+05,3,431,3,1131154
41,477,황해,(주)쇼박스,느와르,2010-12-22,156,청소년 관람불가,나홍진,5.046096e+06,1,683,3,2260512
42,485,끝까지 간다,(주)쇼박스,느와르,2014-05-29,111,15세 관람가,김성훈,4.361015e+05,2,343,2,3450305
43,491,R2B: 리턴투베이스,주머니필름,액션,2012-08-15,113,15세 관람가,김동원,NaN,0,477,7,1201944
44,498,암살,(주)쇼박스,액션,2015-07-22,139,15세 관람가,최동훈,5.169479e+06,4,628,3,12706663
45,516,서부전선,롯데엔터테인먼트,액션,2015-09-24,112,12세 관람가,천성일,4.385472e+06,2,388,2,609063
46,519,보호자,무비꼴라쥬,느와르,2014-04-10,88,15세 관람가,유원상,2.496000e+03,1,128,3,458
47,524,코인라커,(주)드림팩트엔터테인먼트,느와르,2015-05-28,95,청소년 관람불가,김태경,2.283850e+05,1,115,2,1008
48,540,헤드,SBS콘텐츠허브,액션,2011-05-26,100,청소년 관람불가,조운,1.450000e+02,1,290,3,61414
49,543,"협녀, 칼의 기억",롯데엔터테인먼트,액션,2015-08-13,121,15세 관람가,박흥식,1.209303e+05,3,439,3,431310
50,583,창수,(주)마인스 엔터테인먼트,느와르,2013-11-28,103,청소년 관람불가,이덕희,2.810000e+02,1,194,5,429141
51,588,하울링,CJ 엔터테인먼트,느와르,2012-02-16,114,15세 관람가,유하,2.061297e+06,3,288,2,1612554
52,592,차이나타운,CGV아트하우스,느와르,2015-04-29,110,청소년 관람불가,한준희,5.974970e+05,3,420,3,1472147
53,598,악의 연대기,CJ 엔터테인먼트,느와르,2015-05-14,102,15세 관람가,백운학,NaN,0,431,4,2192525
54,599,베를린,CJ 엔터테인먼트,액션,2013-01-30,120,15세 관람가,류승완,NaN,0,363,5,7166532

In [55]:
######## numstaff로 해보기##########

In [57]:
data=action.num_staff

In [58]:
data_dumm=pd.get_dummies(data)

In [59]:
y=target.values